/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as ActualitesRouteImport } from './routes/actualites'
import { Route as AdhesionRouteImport } from './routes/adhesion'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CommentAdhererRouteImport } from './routes/comment-adherer'
import { Route as ConditionsRouteImport } from './routes/conditions'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as EvenementsRouteImport } from './routes/evenements'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GalerieRouteImport } from './routes/galerie'
import { Route as MissionRouteImport } from './routes/mission'
import { Route as PartenairesRouteImport } from './routes/partenaires'
import { Route as PartenariatRouteImport } from './routes/partenariat'
import { Route as RealisationsRouteImport } from './routes/realisations'
import { Route as RecrutementRouteImport } from './routes/recrutement'
import { Route as ReinitialisationRouteImport } from './routes/reinitialisation'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as TelechargementsRouteImport } from './routes/telechargements'
import { Route as TemoignagesRouteImport } from './routes/temoignages'
import { Route as ValeursRouteImport } from './routes/valeurs'
import { Route as VisionRouteImport } from './routes/vision'
import { Route as ActualitesIndexRouteImport } from './routes/actualites.index'
import { Route as ActualitesSlugRouteImport } from './routes/actualites.$slug'
import { Route as EvenementsIndexRouteImport } from './routes/evenements.index'
import { Route as EvenementsSlugRouteImport } from './routes/evenements.$slug'
import { Route as PartenairesIndexRouteImport } from './routes/partenaires.index'
import { Route as PartenairesCentresBienEtreRouteImport } from './routes/partenaires.centres-bien-etre'
import { Route as PartenairesEntreprisesRouteImport } from './routes/partenaires.entreprises'
import { Route as PartenairesHopitauxRouteImport } from './routes/partenaires.hopitaux'
import { Route as PartenairesLaboratoiresRouteImport } from './routes/partenaires.laboratoires'
import { Route as PartenairesPharmaciesRouteImport } from './routes/partenaires.pharmacies'
import { Route as VerifyTokenRouteImport } from './routes/verify.$token'
import { Route as AuthenticatedPortailIndexRouteImport } from './routes/_authenticated/portail.index'
import { Route as AuthenticatedPortailAdherentRouteImport } from './routes/_authenticated/portail.adherent'
import { Route as AuthenticatedPortailAdministrationRouteImport } from './routes/_authenticated/portail.administration'
import { Route as AuthenticatedPortailAgentRouteImport } from './routes/_authenticated/portail.agent'
import { Route as AuthenticatedPortailBeneficiaireRouteImport } from './routes/_authenticated/portail.beneficiaire'
import { Route as AuthenticatedPortailCentreBienEtreRouteImport } from './routes/_authenticated/portail.centre-bien-etre'
import { Route as AuthenticatedPortailCoordinationRouteImport } from './routes/_authenticated/portail.coordination'
import { Route as AuthenticatedPortailDirectionGeneraleRouteImport } from './routes/_authenticated/portail.direction-generale'
import { Route as AuthenticatedPortailEntrepriseRouteImport } from './routes/_authenticated/portail.entreprise'
import { Route as AuthenticatedPortailEspacePartenaireRouteImport } from './routes/_authenticated/portail.espace-partenaire'
import { Route as AuthenticatedPortailFinanceRouteImport } from './routes/_authenticated/portail.finance'
import { Route as AuthenticatedPortailGedRouteImport } from './routes/_authenticated/portail.ged'
import { Route as AuthenticatedPortailHopitalRouteImport } from './routes/_authenticated/portail.hopital'
import { Route as AuthenticatedPortailLaboratoireRouteImport } from './routes/_authenticated/portail.laboratoire'
import { Route as AuthenticatedPortailMedicalRouteImport } from './routes/_authenticated/portail.medical'
import { Route as AuthenticatedPortailMonDossierRouteImport } from './routes/_authenticated/portail.mon-dossier'
import { Route as AuthenticatedPortailNotificationsRouteImport } from './routes/_authenticated/portail.notifications'
import { Route as AuthenticatedPortailParametresRouteImport } from './routes/_authenticated/portail.parametres'
import { Route as AuthenticatedPortailPharmacieRouteImport } from './routes/_authenticated/portail.pharmacie'
import { Route as AuthenticatedPortailRapportsRouteImport } from './routes/_authenticated/portail.rapports'
import { Route as AuthenticatedPortailRhRouteImport } from './routes/_authenticated/portail.rh'
import { Route as AuthenticatedPortailSecuriteRouteImport } from './routes/_authenticated/portail.securite'
import { Route as AuthenticatedPortailAdherentsIndexRouteImport } from './routes/_authenticated/portail.adherents.index'
import { Route as AuthenticatedPortailAdherentsIdRouteImport } from './routes/_authenticated/portail.adherents.$id'
import { Route as AuthenticatedPortailCartesIndexRouteImport } from './routes/_authenticated/portail.cartes.index'
import { Route as AuthenticatedPortailCotisationsIndexRouteImport } from './routes/_authenticated/portail.cotisations.index'
import { Route as AuthenticatedPortailPartenairesIndexRouteImport } from './routes/_authenticated/portail.partenaires.index'
import { Route as AuthenticatedPortailPartenairesIdRouteImport } from './routes/_authenticated/portail.partenaires.$id'
import { Route as AuthenticatedPortailPrisesEnChargeIndexRouteImport } from './routes/_authenticated/portail.prises-en-charge.index'
import { Route as AuthenticatedPortailRemboursementsIndexRouteImport } from './routes/_authenticated/portail.remboursements.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesRoute = ActualitesRouteImport.update({
  id: '/actualites',
  path: '/actualites',
  getParentRoute: () => rootRouteImport,
} as any)
const AdhesionRoute = AdhesionRouteImport.update({
  id: '/adhesion',
  path: '/adhesion',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentAdhererRoute = CommentAdhererRouteImport.update({
  id: '/comment-adherer',
  path: '/comment-adherer',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsRoute = ConditionsRouteImport.update({
  id: '/conditions',
  path: '/conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const EvenementsRoute = EvenementsRouteImport.update({
  id: '/evenements',
  path: '/evenements',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GalerieRoute = GalerieRouteImport.update({
  id: '/galerie',
  path: '/galerie',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionRoute = MissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const PartenairesRoute = PartenairesRouteImport.update({
  id: '/partenaires',
  path: '/partenaires',
  getParentRoute: () => rootRouteImport,
} as any)
const PartenariatRoute = PartenariatRouteImport.update({
  id: '/partenariat',
  path: '/partenariat',
  getParentRoute: () => rootRouteImport,
} as any)
const RealisationsRoute = RealisationsRouteImport.update({
  id: '/realisations',
  path: '/realisations',
  getParentRoute: () => rootRouteImport,
} as any)
const RecrutementRoute = RecrutementRouteImport.update({
  id: '/recrutement',
  path: '/recrutement',
  getParentRoute: () => rootRouteImport,
} as any)
const ReinitialisationRoute = ReinitialisationRouteImport.update({
  id: '/reinitialisation',
  path: '/reinitialisation',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const TelechargementsRoute = TelechargementsRouteImport.update({
  id: '/telechargements',
  path: '/telechargements',
  getParentRoute: () => rootRouteImport,
} as any)
const TemoignagesRoute = TemoignagesRouteImport.update({
  id: '/temoignages',
  path: '/temoignages',
  getParentRoute: () => rootRouteImport,
} as any)
const ValeursRoute = ValeursRouteImport.update({
  id: '/valeurs',
  path: '/valeurs',
  getParentRoute: () => rootRouteImport,
} as any)
const VisionRoute = VisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesIndexRoute = ActualitesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ActualitesRoute,
} as any)
const ActualitesSlugRoute = ActualitesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ActualitesRoute,
} as any)
const EvenementsIndexRoute = EvenementsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EvenementsRoute,
} as any)
const EvenementsSlugRoute = EvenementsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EvenementsRoute,
} as any)
const PartenairesIndexRoute = PartenairesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PartenairesRoute,
} as any)
const PartenairesCentresBienEtreRoute =
  PartenairesCentresBienEtreRouteImport.update({
    id: '/centres-bien-etre',
    path: '/centres-bien-etre',
    getParentRoute: () => PartenairesRoute,
  } as any)
const PartenairesEntreprisesRoute = PartenairesEntreprisesRouteImport.update({
  id: '/entreprises',
  path: '/entreprises',
  getParentRoute: () => PartenairesRoute,
} as any)
const PartenairesHopitauxRoute = PartenairesHopitauxRouteImport.update({
  id: '/hopitaux',
  path: '/hopitaux',
  getParentRoute: () => PartenairesRoute,
} as any)
const PartenairesLaboratoiresRoute = PartenairesLaboratoiresRouteImport.update({
  id: '/laboratoires',
  path: '/laboratoires',
  getParentRoute: () => PartenairesRoute,
} as any)
const PartenairesPharmaciesRoute = PartenairesPharmaciesRouteImport.update({
  id: '/pharmacies',
  path: '/pharmacies',
  getParentRoute: () => PartenairesRoute,
} as any)
const VerifyTokenRoute = VerifyTokenRouteImport.update({
  id: '/verify/$token',
  path: '/verify/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortailIndexRoute =
  AuthenticatedPortailIndexRouteImport.update({
    id: '/portail/',
    path: '/portail/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortailAdherentRoute =
  AuthenticatedPortailAdherentRouteImport.update({
    id: '/portail/adherent',
    path: '/portail/adherent',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortailAdministrationRoute =
  AuthenticatedPortailAdministrationRouteImport.update({
    id: '/portail/administration',
    path: '/portail/administration',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortailAgentRoute =
  AuthenticatedPortailAgentRouteImport.update({
    id: '/portail/agent',
    path: '/portail/agent',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortailBeneficiaireRoute =
  AuthenticatedPortailBeneficiaireRouteImport.update({
    id: '/portail/beneficiaire',
    path: '/portail/beneficiaire',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortailCentreBienEtreRoute =
  AuthenticatedPortailCentreBienEtreRouteImport.update({
    id: '/portail/centre-bien-etre',
    path: '/portail/centre-bien-etre',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortailCoordinationRoute =
  AuthenticatedPortailCoordinationRouteImport.update({
    id: '/portail/coordination',
    path: '/portail/coordination',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortailDirectionGeneraleRoute =
  AuthenticatedPortailDirectionGeneraleRouteImport.update({
    id: '/portail/direction-generale',
    path: '/portail/direction-generale',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortailEntrepriseRoute =
  AuthenticatedPortailEntrepriseRouteImport.update({
    id: '/portail/entreprise',
    path: '/portail/entreprise',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortailEspacePartenaireRoute =
  AuthenticatedPortailEspacePartenaireRouteImport.update({
    id: '/portail/espace-partenaire',
    path: '/portail/espace-partenaire',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortailFinanceRoute =
  AuthenticatedPortailFinanceRouteImport.update({
    id: '/portail/finance',
    path: '/portail/finance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortailGedRoute = AuthenticatedPortailGedRouteImport.update({
  id: '/portail/ged',
  path: '/portail/ged',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortailHopitalRoute =
  AuthenticatedPortailHopitalRouteImport.update({
    id: '/portail/hopital',
    path: '/portail/hopital',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortailLaboratoireRoute =
  AuthenticatedPortailLaboratoireRouteImport.update({
    id: '/portail/laboratoire',
    path: '/portail/laboratoire',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortailMedicalRoute =
  AuthenticatedPortailMedicalRouteImport.update({
    id: '/portail/medical',
    path: '/portail/medical',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortailMonDossierRoute =
  AuthenticatedPortailMonDossierRouteImport.update({
    id: '/portail/mon-dossier',
    path: '/portail/mon-dossier',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortailNotificationsRoute =
  AuthenticatedPortailNotificationsRouteImport.update({
    id: '/portail/notifications',
    path: '/portail/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortailParametresRoute =
  AuthenticatedPortailParametresRouteImport.update({
    id: '/portail/parametres',
    path: '/portail/parametres',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortailPharmacieRoute =
  AuthenticatedPortailPharmacieRouteImport.update({
    id: '/portail/pharmacie',
    path: '/portail/pharmacie',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortailRapportsRoute =
  AuthenticatedPortailRapportsRouteImport.update({
    id: '/portail/rapports',
    path: '/portail/rapports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortailRhRoute = AuthenticatedPortailRhRouteImport.update({
  id: '/portail/rh',
  path: '/portail/rh',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortailSecuriteRoute =
  AuthenticatedPortailSecuriteRouteImport.update({
    id: '/portail/securite',
    path: '/portail/securite',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortailAdherentsIndexRoute =
  AuthenticatedPortailAdherentsIndexRouteImport.update({
    id: '/portail/adherents/',
    path: '/portail/adherents/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortailAdherentsIdRoute =
  AuthenticatedPortailAdherentsIdRouteImport.update({
    id: '/portail/adherents/$id',
    path: '/portail/adherents/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortailCartesIndexRoute =
  AuthenticatedPortailCartesIndexRouteImport.update({
    id: '/portail/cartes/',
    path: '/portail/cartes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortailCotisationsIndexRoute =
  AuthenticatedPortailCotisationsIndexRouteImport.update({
    id: '/portail/cotisations/',
    path: '/portail/cotisations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortailPartenairesIndexRoute =
  AuthenticatedPortailPartenairesIndexRouteImport.update({
    id: '/portail/partenaires/',
    path: '/portail/partenaires/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortailPartenairesIdRoute =
  AuthenticatedPortailPartenairesIdRouteImport.update({
    id: '/portail/partenaires/$id',
    path: '/portail/partenaires/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortailPrisesEnChargeIndexRoute =
  AuthenticatedPortailPrisesEnChargeIndexRouteImport.update({
    id: '/portail/prises-en-charge/',
    path: '/portail/prises-en-charge/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortailRemboursementsIndexRoute =
  AuthenticatedPortailRemboursementsIndexRouteImport.update({
    id: '/portail/remboursements/',
    path: '/portail/remboursements/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/actualites': typeof ActualitesRouteWithChildren
  '/adhesion': typeof AdhesionRoute
  '/auth': typeof AuthRoute
  '/comment-adherer': typeof CommentAdhererRoute
  '/conditions': typeof ConditionsRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/equipe': typeof EquipeRoute
  '/evenements': typeof EvenementsRouteWithChildren
  '/faq': typeof FaqRoute
  '/galerie': typeof GalerieRoute
  '/mission': typeof MissionRoute
  '/partenaires': typeof PartenairesRouteWithChildren
  '/partenariat': typeof PartenariatRoute
  '/realisations': typeof RealisationsRoute
  '/recrutement': typeof RecrutementRoute
  '/reinitialisation': typeof ReinitialisationRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarifs': typeof TarifsRoute
  '/telechargements': typeof TelechargementsRoute
  '/temoignages': typeof TemoignagesRoute
  '/valeurs': typeof ValeursRoute
  '/vision': typeof VisionRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/evenements/$slug': typeof EvenementsSlugRoute
  '/partenaires/centres-bien-etre': typeof PartenairesCentresBienEtreRoute
  '/partenaires/entreprises': typeof PartenairesEntreprisesRoute
  '/partenaires/hopitaux': typeof PartenairesHopitauxRoute
  '/partenaires/laboratoires': typeof PartenairesLaboratoiresRoute
  '/partenaires/pharmacies': typeof PartenairesPharmaciesRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/actualites/': typeof ActualitesIndexRoute
  '/evenements/': typeof EvenementsIndexRoute
  '/partenaires/': typeof PartenairesIndexRoute
  '/portail/adherent': typeof AuthenticatedPortailAdherentRoute
  '/portail/administration': typeof AuthenticatedPortailAdministrationRoute
  '/portail/agent': typeof AuthenticatedPortailAgentRoute
  '/portail/beneficiaire': typeof AuthenticatedPortailBeneficiaireRoute
  '/portail/centre-bien-etre': typeof AuthenticatedPortailCentreBienEtreRoute
  '/portail/coordination': typeof AuthenticatedPortailCoordinationRoute
  '/portail/direction-generale': typeof AuthenticatedPortailDirectionGeneraleRoute
  '/portail/entreprise': typeof AuthenticatedPortailEntrepriseRoute
  '/portail/espace-partenaire': typeof AuthenticatedPortailEspacePartenaireRoute
  '/portail/finance': typeof AuthenticatedPortailFinanceRoute
  '/portail/ged': typeof AuthenticatedPortailGedRoute
  '/portail/hopital': typeof AuthenticatedPortailHopitalRoute
  '/portail/laboratoire': typeof AuthenticatedPortailLaboratoireRoute
  '/portail/medical': typeof AuthenticatedPortailMedicalRoute
  '/portail/mon-dossier': typeof AuthenticatedPortailMonDossierRoute
  '/portail/notifications': typeof AuthenticatedPortailNotificationsRoute
  '/portail/parametres': typeof AuthenticatedPortailParametresRoute
  '/portail/pharmacie': typeof AuthenticatedPortailPharmacieRoute
  '/portail/rapports': typeof AuthenticatedPortailRapportsRoute
  '/portail/rh': typeof AuthenticatedPortailRhRoute
  '/portail/securite': typeof AuthenticatedPortailSecuriteRoute
  '/portail/': typeof AuthenticatedPortailIndexRoute
  '/portail/adherents/$id': typeof AuthenticatedPortailAdherentsIdRoute
  '/portail/partenaires/$id': typeof AuthenticatedPortailPartenairesIdRoute
  '/portail/adherents/': typeof AuthenticatedPortailAdherentsIndexRoute
  '/portail/cartes/': typeof AuthenticatedPortailCartesIndexRoute
  '/portail/cotisations/': typeof AuthenticatedPortailCotisationsIndexRoute
  '/portail/partenaires/': typeof AuthenticatedPortailPartenairesIndexRoute
  '/portail/prises-en-charge/': typeof AuthenticatedPortailPrisesEnChargeIndexRoute
  '/portail/remboursements/': typeof AuthenticatedPortailRemboursementsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/adhesion': typeof AdhesionRoute
  '/auth': typeof AuthRoute
  '/comment-adherer': typeof CommentAdhererRoute
  '/conditions': typeof ConditionsRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/equipe': typeof EquipeRoute
  '/faq': typeof FaqRoute
  '/galerie': typeof GalerieRoute
  '/mission': typeof MissionRoute
  '/partenariat': typeof PartenariatRoute
  '/realisations': typeof RealisationsRoute
  '/recrutement': typeof RecrutementRoute
  '/reinitialisation': typeof ReinitialisationRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarifs': typeof TarifsRoute
  '/telechargements': typeof TelechargementsRoute
  '/temoignages': typeof TemoignagesRoute
  '/valeurs': typeof ValeursRoute
  '/vision': typeof VisionRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/evenements/$slug': typeof EvenementsSlugRoute
  '/partenaires/centres-bien-etre': typeof PartenairesCentresBienEtreRoute
  '/partenaires/entreprises': typeof PartenairesEntreprisesRoute
  '/partenaires/hopitaux': typeof PartenairesHopitauxRoute
  '/partenaires/laboratoires': typeof PartenairesLaboratoiresRoute
  '/partenaires/pharmacies': typeof PartenairesPharmaciesRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/actualites': typeof ActualitesIndexRoute
  '/evenements': typeof EvenementsIndexRoute
  '/partenaires': typeof PartenairesIndexRoute
  '/portail/adherent': typeof AuthenticatedPortailAdherentRoute
  '/portail/administration': typeof AuthenticatedPortailAdministrationRoute
  '/portail/agent': typeof AuthenticatedPortailAgentRoute
  '/portail/beneficiaire': typeof AuthenticatedPortailBeneficiaireRoute
  '/portail/centre-bien-etre': typeof AuthenticatedPortailCentreBienEtreRoute
  '/portail/coordination': typeof AuthenticatedPortailCoordinationRoute
  '/portail/direction-generale': typeof AuthenticatedPortailDirectionGeneraleRoute
  '/portail/entreprise': typeof AuthenticatedPortailEntrepriseRoute
  '/portail/espace-partenaire': typeof AuthenticatedPortailEspacePartenaireRoute
  '/portail/finance': typeof AuthenticatedPortailFinanceRoute
  '/portail/ged': typeof AuthenticatedPortailGedRoute
  '/portail/hopital': typeof AuthenticatedPortailHopitalRoute
  '/portail/laboratoire': typeof AuthenticatedPortailLaboratoireRoute
  '/portail/medical': typeof AuthenticatedPortailMedicalRoute
  '/portail/mon-dossier': typeof AuthenticatedPortailMonDossierRoute
  '/portail/notifications': typeof AuthenticatedPortailNotificationsRoute
  '/portail/parametres': typeof AuthenticatedPortailParametresRoute
  '/portail/pharmacie': typeof AuthenticatedPortailPharmacieRoute
  '/portail/rapports': typeof AuthenticatedPortailRapportsRoute
  '/portail/rh': typeof AuthenticatedPortailRhRoute
  '/portail/securite': typeof AuthenticatedPortailSecuriteRoute
  '/portail': typeof AuthenticatedPortailIndexRoute
  '/portail/adherents/$id': typeof AuthenticatedPortailAdherentsIdRoute
  '/portail/partenaires/$id': typeof AuthenticatedPortailPartenairesIdRoute
  '/portail/adherents': typeof AuthenticatedPortailAdherentsIndexRoute
  '/portail/cartes': typeof AuthenticatedPortailCartesIndexRoute
  '/portail/cotisations': typeof AuthenticatedPortailCotisationsIndexRoute
  '/portail/partenaires': typeof AuthenticatedPortailPartenairesIndexRoute
  '/portail/prises-en-charge': typeof AuthenticatedPortailPrisesEnChargeIndexRoute
  '/portail/remboursements': typeof AuthenticatedPortailRemboursementsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/a-propos': typeof AProposRoute
  '/actualites': typeof ActualitesRouteWithChildren
  '/adhesion': typeof AdhesionRoute
  '/auth': typeof AuthRoute
  '/comment-adherer': typeof CommentAdhererRoute
  '/conditions': typeof ConditionsRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/equipe': typeof EquipeRoute
  '/evenements': typeof EvenementsRouteWithChildren
  '/faq': typeof FaqRoute
  '/galerie': typeof GalerieRoute
  '/mission': typeof MissionRoute
  '/partenaires': typeof PartenairesRouteWithChildren
  '/partenariat': typeof PartenariatRoute
  '/realisations': typeof RealisationsRoute
  '/recrutement': typeof RecrutementRoute
  '/reinitialisation': typeof ReinitialisationRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarifs': typeof TarifsRoute
  '/telechargements': typeof TelechargementsRoute
  '/temoignages': typeof TemoignagesRoute
  '/valeurs': typeof ValeursRoute
  '/vision': typeof VisionRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/evenements/$slug': typeof EvenementsSlugRoute
  '/partenaires/centres-bien-etre': typeof PartenairesCentresBienEtreRoute
  '/partenaires/entreprises': typeof PartenairesEntreprisesRoute
  '/partenaires/hopitaux': typeof PartenairesHopitauxRoute
  '/partenaires/laboratoires': typeof PartenairesLaboratoiresRoute
  '/partenaires/pharmacies': typeof PartenairesPharmaciesRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/actualites/': typeof ActualitesIndexRoute
  '/evenements/': typeof EvenementsIndexRoute
  '/partenaires/': typeof PartenairesIndexRoute
  '/_authenticated/portail/adherent': typeof AuthenticatedPortailAdherentRoute
  '/_authenticated/portail/administration': typeof AuthenticatedPortailAdministrationRoute
  '/_authenticated/portail/agent': typeof AuthenticatedPortailAgentRoute
  '/_authenticated/portail/beneficiaire': typeof AuthenticatedPortailBeneficiaireRoute
  '/_authenticated/portail/centre-bien-etre': typeof AuthenticatedPortailCentreBienEtreRoute
  '/_authenticated/portail/coordination': typeof AuthenticatedPortailCoordinationRoute
  '/_authenticated/portail/direction-generale': typeof AuthenticatedPortailDirectionGeneraleRoute
  '/_authenticated/portail/entreprise': typeof AuthenticatedPortailEntrepriseRoute
  '/_authenticated/portail/espace-partenaire': typeof AuthenticatedPortailEspacePartenaireRoute
  '/_authenticated/portail/finance': typeof AuthenticatedPortailFinanceRoute
  '/_authenticated/portail/ged': typeof AuthenticatedPortailGedRoute
  '/_authenticated/portail/hopital': typeof AuthenticatedPortailHopitalRoute
  '/_authenticated/portail/laboratoire': typeof AuthenticatedPortailLaboratoireRoute
  '/_authenticated/portail/medical': typeof AuthenticatedPortailMedicalRoute
  '/_authenticated/portail/mon-dossier': typeof AuthenticatedPortailMonDossierRoute
  '/_authenticated/portail/notifications': typeof AuthenticatedPortailNotificationsRoute
  '/_authenticated/portail/parametres': typeof AuthenticatedPortailParametresRoute
  '/_authenticated/portail/pharmacie': typeof AuthenticatedPortailPharmacieRoute
  '/_authenticated/portail/rapports': typeof AuthenticatedPortailRapportsRoute
  '/_authenticated/portail/rh': typeof AuthenticatedPortailRhRoute
  '/_authenticated/portail/securite': typeof AuthenticatedPortailSecuriteRoute
  '/_authenticated/portail/': typeof AuthenticatedPortailIndexRoute
  '/_authenticated/portail/adherents/$id': typeof AuthenticatedPortailAdherentsIdRoute
  '/_authenticated/portail/partenaires/$id': typeof AuthenticatedPortailPartenairesIdRoute
  '/_authenticated/portail/adherents/': typeof AuthenticatedPortailAdherentsIndexRoute
  '/_authenticated/portail/cartes/': typeof AuthenticatedPortailCartesIndexRoute
  '/_authenticated/portail/cotisations/': typeof AuthenticatedPortailCotisationsIndexRoute
  '/_authenticated/portail/partenaires/': typeof AuthenticatedPortailPartenairesIndexRoute
  '/_authenticated/portail/prises-en-charge/': typeof AuthenticatedPortailPrisesEnChargeIndexRoute
  '/_authenticated/portail/remboursements/': typeof AuthenticatedPortailRemboursementsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/actualites'
    | '/adhesion'
    | '/auth'
    | '/comment-adherer'
    | '/conditions'
    | '/confidentialite'
    | '/connexion'
    | '/contact'
    | '/equipe'
    | '/evenements'
    | '/faq'
    | '/galerie'
    | '/mission'
    | '/partenaires'
    | '/partenariat'
    | '/realisations'
    | '/recrutement'
    | '/reinitialisation'
    | '/services'
    | '/sitemap.xml'
    | '/tarifs'
    | '/telechargements'
    | '/temoignages'
    | '/valeurs'
    | '/vision'
    | '/actualites/$slug'
    | '/evenements/$slug'
    | '/partenaires/centres-bien-etre'
    | '/partenaires/entreprises'
    | '/partenaires/hopitaux'
    | '/partenaires/laboratoires'
    | '/partenaires/pharmacies'
    | '/verify/$token'
    | '/actualites/'
    | '/evenements/'
    | '/partenaires/'
    | '/portail/adherent'
    | '/portail/administration'
    | '/portail/agent'
    | '/portail/beneficiaire'
    | '/portail/centre-bien-etre'
    | '/portail/coordination'
    | '/portail/direction-generale'
    | '/portail/entreprise'
    | '/portail/espace-partenaire'
    | '/portail/finance'
    | '/portail/ged'
    | '/portail/hopital'
    | '/portail/laboratoire'
    | '/portail/medical'
    | '/portail/mon-dossier'
    | '/portail/notifications'
    | '/portail/parametres'
    | '/portail/pharmacie'
    | '/portail/rapports'
    | '/portail/rh'
    | '/portail/securite'
    | '/portail/'
    | '/portail/adherents/$id'
    | '/portail/partenaires/$id'
    | '/portail/adherents/'
    | '/portail/cartes/'
    | '/portail/cotisations/'
    | '/portail/partenaires/'
    | '/portail/prises-en-charge/'
    | '/portail/remboursements/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/adhesion'
    | '/auth'
    | '/comment-adherer'
    | '/conditions'
    | '/confidentialite'
    | '/connexion'
    | '/contact'
    | '/equipe'
    | '/faq'
    | '/galerie'
    | '/mission'
    | '/partenariat'
    | '/realisations'
    | '/recrutement'
    | '/reinitialisation'
    | '/services'
    | '/sitemap.xml'
    | '/tarifs'
    | '/telechargements'
    | '/temoignages'
    | '/valeurs'
    | '/vision'
    | '/actualites/$slug'
    | '/evenements/$slug'
    | '/partenaires/centres-bien-etre'
    | '/partenaires/entreprises'
    | '/partenaires/hopitaux'
    | '/partenaires/laboratoires'
    | '/partenaires/pharmacies'
    | '/verify/$token'
    | '/actualites'
    | '/evenements'
    | '/partenaires'
    | '/portail/adherent'
    | '/portail/administration'
    | '/portail/agent'
    | '/portail/beneficiaire'
    | '/portail/centre-bien-etre'
    | '/portail/coordination'
    | '/portail/direction-generale'
    | '/portail/entreprise'
    | '/portail/espace-partenaire'
    | '/portail/finance'
    | '/portail/ged'
    | '/portail/hopital'
    | '/portail/laboratoire'
    | '/portail/medical'
    | '/portail/mon-dossier'
    | '/portail/notifications'
    | '/portail/parametres'
    | '/portail/pharmacie'
    | '/portail/rapports'
    | '/portail/rh'
    | '/portail/securite'
    | '/portail'
    | '/portail/adherents/$id'
    | '/portail/partenaires/$id'
    | '/portail/adherents'
    | '/portail/cartes'
    | '/portail/cotisations'
    | '/portail/partenaires'
    | '/portail/prises-en-charge'
    | '/portail/remboursements'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/a-propos'
    | '/actualites'
    | '/adhesion'
    | '/auth'
    | '/comment-adherer'
    | '/conditions'
    | '/confidentialite'
    | '/connexion'
    | '/contact'
    | '/equipe'
    | '/evenements'
    | '/faq'
    | '/galerie'
    | '/mission'
    | '/partenaires'
    | '/partenariat'
    | '/realisations'
    | '/recrutement'
    | '/reinitialisation'
    | '/services'
    | '/sitemap.xml'
    | '/tarifs'
    | '/telechargements'
    | '/temoignages'
    | '/valeurs'
    | '/vision'
    | '/actualites/$slug'
    | '/evenements/$slug'
    | '/partenaires/centres-bien-etre'
    | '/partenaires/entreprises'
    | '/partenaires/hopitaux'
    | '/partenaires/laboratoires'
    | '/partenaires/pharmacies'
    | '/verify/$token'
    | '/actualites/'
    | '/evenements/'
    | '/partenaires/'
    | '/_authenticated/portail/adherent'
    | '/_authenticated/portail/administration'
    | '/_authenticated/portail/agent'
    | '/_authenticated/portail/beneficiaire'
    | '/_authenticated/portail/centre-bien-etre'
    | '/_authenticated/portail/coordination'
    | '/_authenticated/portail/direction-generale'
    | '/_authenticated/portail/entreprise'
    | '/_authenticated/portail/espace-partenaire'
    | '/_authenticated/portail/finance'
    | '/_authenticated/portail/ged'
    | '/_authenticated/portail/hopital'
    | '/_authenticated/portail/laboratoire'
    | '/_authenticated/portail/medical'
    | '/_authenticated/portail/mon-dossier'
    | '/_authenticated/portail/notifications'
    | '/_authenticated/portail/parametres'
    | '/_authenticated/portail/pharmacie'
    | '/_authenticated/portail/rapports'
    | '/_authenticated/portail/rh'
    | '/_authenticated/portail/securite'
    | '/_authenticated/portail/'
    | '/_authenticated/portail/adherents/$id'
    | '/_authenticated/portail/partenaires/$id'
    | '/_authenticated/portail/adherents/'
    | '/_authenticated/portail/cartes/'
    | '/_authenticated/portail/cotisations/'
    | '/_authenticated/portail/partenaires/'
    | '/_authenticated/portail/prises-en-charge/'
    | '/_authenticated/portail/remboursements/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AProposRoute: typeof AProposRoute
  ActualitesRoute: typeof ActualitesRouteWithChildren
  AdhesionRoute: typeof AdhesionRoute
  AuthRoute: typeof AuthRoute
  CommentAdhererRoute: typeof CommentAdhererRoute
  ConditionsRoute: typeof ConditionsRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ConnexionRoute: typeof ConnexionRoute
  ContactRoute: typeof ContactRoute
  EquipeRoute: typeof EquipeRoute
  EvenementsRoute: typeof EvenementsRouteWithChildren
  FaqRoute: typeof FaqRoute
  GalerieRoute: typeof GalerieRoute
  MissionRoute: typeof MissionRoute
  PartenairesRoute: typeof PartenairesRouteWithChildren
  PartenariatRoute: typeof PartenariatRoute
  RealisationsRoute: typeof RealisationsRoute
  RecrutementRoute: typeof RecrutementRoute
  ReinitialisationRoute: typeof ReinitialisationRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TarifsRoute: typeof TarifsRoute
  TelechargementsRoute: typeof TelechargementsRoute
  TemoignagesRoute: typeof TemoignagesRoute
  ValeursRoute: typeof ValeursRoute
  VisionRoute: typeof VisionRoute
  VerifyTokenRoute: typeof VerifyTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites': {
      id: '/actualites'
      path: '/actualites'
      fullPath: '/actualites'
      preLoaderRoute: typeof ActualitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adhesion': {
      id: '/adhesion'
      path: '/adhesion'
      fullPath: '/adhesion'
      preLoaderRoute: typeof AdhesionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comment-adherer': {
      id: '/comment-adherer'
      path: '/comment-adherer'
      fullPath: '/comment-adherer'
      preLoaderRoute: typeof CommentAdhererRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions': {
      id: '/conditions'
      path: '/conditions'
      fullPath: '/conditions'
      preLoaderRoute: typeof ConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evenements': {
      id: '/evenements'
      path: '/evenements'
      fullPath: '/evenements'
      preLoaderRoute: typeof EvenementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galerie': {
      id: '/galerie'
      path: '/galerie'
      fullPath: '/galerie'
      preLoaderRoute: typeof GalerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission': {
      id: '/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof MissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partenaires': {
      id: '/partenaires'
      path: '/partenaires'
      fullPath: '/partenaires'
      preLoaderRoute: typeof PartenairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partenariat': {
      id: '/partenariat'
      path: '/partenariat'
      fullPath: '/partenariat'
      preLoaderRoute: typeof PartenariatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realisations': {
      id: '/realisations'
      path: '/realisations'
      fullPath: '/realisations'
      preLoaderRoute: typeof RealisationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recrutement': {
      id: '/recrutement'
      path: '/recrutement'
      fullPath: '/recrutement'
      preLoaderRoute: typeof RecrutementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reinitialisation': {
      id: '/reinitialisation'
      path: '/reinitialisation'
      fullPath: '/reinitialisation'
      preLoaderRoute: typeof ReinitialisationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telechargements': {
      id: '/telechargements'
      path: '/telechargements'
      fullPath: '/telechargements'
      preLoaderRoute: typeof TelechargementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temoignages': {
      id: '/temoignages'
      path: '/temoignages'
      fullPath: '/temoignages'
      preLoaderRoute: typeof TemoignagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/valeurs': {
      id: '/valeurs'
      path: '/valeurs'
      fullPath: '/valeurs'
      preLoaderRoute: typeof ValeursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vision': {
      id: '/vision'
      path: '/vision'
      fullPath: '/vision'
      preLoaderRoute: typeof VisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites/': {
      id: '/actualites/'
      path: '/'
      fullPath: '/actualites/'
      preLoaderRoute: typeof ActualitesIndexRouteImport
      parentRoute: typeof ActualitesRoute
    }
    '/actualites/$slug': {
      id: '/actualites/$slug'
      path: '/$slug'
      fullPath: '/actualites/$slug'
      preLoaderRoute: typeof ActualitesSlugRouteImport
      parentRoute: typeof ActualitesRoute
    }
    '/evenements/': {
      id: '/evenements/'
      path: '/'
      fullPath: '/evenements/'
      preLoaderRoute: typeof EvenementsIndexRouteImport
      parentRoute: typeof EvenementsRoute
    }
    '/evenements/$slug': {
      id: '/evenements/$slug'
      path: '/$slug'
      fullPath: '/evenements/$slug'
      preLoaderRoute: typeof EvenementsSlugRouteImport
      parentRoute: typeof EvenementsRoute
    }
    '/partenaires/': {
      id: '/partenaires/'
      path: '/'
      fullPath: '/partenaires/'
      preLoaderRoute: typeof PartenairesIndexRouteImport
      parentRoute: typeof PartenairesRoute
    }
    '/partenaires/centres-bien-etre': {
      id: '/partenaires/centres-bien-etre'
      path: '/centres-bien-etre'
      fullPath: '/partenaires/centres-bien-etre'
      preLoaderRoute: typeof PartenairesCentresBienEtreRouteImport
      parentRoute: typeof PartenairesRoute
    }
    '/partenaires/entreprises': {
      id: '/partenaires/entreprises'
      path: '/entreprises'
      fullPath: '/partenaires/entreprises'
      preLoaderRoute: typeof PartenairesEntreprisesRouteImport
      parentRoute: typeof PartenairesRoute
    }
    '/partenaires/hopitaux': {
      id: '/partenaires/hopitaux'
      path: '/hopitaux'
      fullPath: '/partenaires/hopitaux'
      preLoaderRoute: typeof PartenairesHopitauxRouteImport
      parentRoute: typeof PartenairesRoute
    }
    '/partenaires/laboratoires': {
      id: '/partenaires/laboratoires'
      path: '/laboratoires'
      fullPath: '/partenaires/laboratoires'
      preLoaderRoute: typeof PartenairesLaboratoiresRouteImport
      parentRoute: typeof PartenairesRoute
    }
    '/partenaires/pharmacies': {
      id: '/partenaires/pharmacies'
      path: '/pharmacies'
      fullPath: '/partenaires/pharmacies'
      preLoaderRoute: typeof PartenairesPharmaciesRouteImport
      parentRoute: typeof PartenairesRoute
    }
    '/verify/$token': {
      id: '/verify/$token'
      path: '/verify/$token'
      fullPath: '/verify/$token'
      preLoaderRoute: typeof VerifyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portail/': {
      id: '/_authenticated/portail/'
      path: '/portail'
      fullPath: '/portail/'
      preLoaderRoute: typeof AuthenticatedPortailIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portail/adherent': {
      id: '/_authenticated/portail/adherent'
      path: '/portail/adherent'
      fullPath: '/portail/adherent'
      preLoaderRoute: typeof AuthenticatedPortailAdherentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portail/administration': {
      id: '/_authenticated/portail/administration'
      path: '/portail/administration'
      fullPath: '/portail/administration'
      preLoaderRoute: typeof AuthenticatedPortailAdministrationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portail/agent': {
      id: '/_authenticated/portail/agent'
      path: '/portail/agent'
      fullPath: '/portail/agent'
      preLoaderRoute: typeof AuthenticatedPortailAgentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portail/beneficiaire': {
      id: '/_authenticated/portail/beneficiaire'
      path: '/portail/beneficiaire'
      fullPath: '/portail/beneficiaire'
      preLoaderRoute: typeof AuthenticatedPortailBeneficiaireRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portail/centre-bien-etre': {
      id: '/_authenticated/portail/centre-bien-etre'
      path: '/portail/centre-bien-etre'
      fullPath: '/portail/centre-bien-etre'
      preLoaderRoute: typeof AuthenticatedPortailCentreBienEtreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portail/coordination': {
      id: '/_authenticated/portail/coordination'
      path: '/portail/coordination'
      fullPath: '/portail/coordination'
      preLoaderRoute: typeof AuthenticatedPortailCoordinationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portail/direction-generale': {
      id: '/_authenticated/portail/direction-generale'
      path: '/portail/direction-generale'
      fullPath: '/portail/direction-generale'
      preLoaderRoute: typeof AuthenticatedPortailDirectionGeneraleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portail/entreprise': {
      id: '/_authenticated/portail/entreprise'
      path: '/portail/entreprise'
      fullPath: '/portail/entreprise'
      preLoaderRoute: typeof AuthenticatedPortailEntrepriseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portail/espace-partenaire': {
      id: '/_authenticated/portail/espace-partenaire'
      path: '/portail/espace-partenaire'
      fullPath: '/portail/espace-partenaire'
      preLoaderRoute: typeof AuthenticatedPortailEspacePartenaireRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portail/finance': {
      id: '/_authenticated/portail/finance'
      path: '/portail/finance'
      fullPath: '/portail/finance'
      preLoaderRoute: typeof AuthenticatedPortailFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portail/ged': {
      id: '/_authenticated/portail/ged'
      path: '/portail/ged'
      fullPath: '/portail/ged'
      preLoaderRoute: typeof AuthenticatedPortailGedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portail/hopital': {
      id: '/_authenticated/portail/hopital'
      path: '/portail/hopital'
      fullPath: '/portail/hopital'
      preLoaderRoute: typeof AuthenticatedPortailHopitalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portail/laboratoire': {
      id: '/_authenticated/portail/laboratoire'
      path: '/portail/laboratoire'
      fullPath: '/portail/laboratoire'
      preLoaderRoute: typeof AuthenticatedPortailLaboratoireRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portail/medical': {
      id: '/_authenticated/portail/medical'
      path: '/portail/medical'
      fullPath: '/portail/medical'
      preLoaderRoute: typeof AuthenticatedPortailMedicalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portail/mon-dossier': {
      id: '/_authenticated/portail/mon-dossier'
      path: '/portail/mon-dossier'
      fullPath: '/portail/mon-dossier'
      preLoaderRoute: typeof AuthenticatedPortailMonDossierRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portail/notifications': {
      id: '/_authenticated/portail/notifications'
      path: '/portail/notifications'
      fullPath: '/portail/notifications'
      preLoaderRoute: typeof AuthenticatedPortailNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portail/parametres': {
      id: '/_authenticated/portail/parametres'
      path: '/portail/parametres'
      fullPath: '/portail/parametres'
      preLoaderRoute: typeof AuthenticatedPortailParametresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portail/pharmacie': {
      id: '/_authenticated/portail/pharmacie'
      path: '/portail/pharmacie'
      fullPath: '/portail/pharmacie'
      preLoaderRoute: typeof AuthenticatedPortailPharmacieRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portail/rapports': {
      id: '/_authenticated/portail/rapports'
      path: '/portail/rapports'
      fullPath: '/portail/rapports'
      preLoaderRoute: typeof AuthenticatedPortailRapportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portail/rh': {
      id: '/_authenticated/portail/rh'
      path: '/portail/rh'
      fullPath: '/portail/rh'
      preLoaderRoute: typeof AuthenticatedPortailRhRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portail/securite': {
      id: '/_authenticated/portail/securite'
      path: '/portail/securite'
      fullPath: '/portail/securite'
      preLoaderRoute: typeof AuthenticatedPortailSecuriteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portail/adherents/': {
      id: '/_authenticated/portail/adherents/'
      path: '/portail/adherents'
      fullPath: '/portail/adherents/'
      preLoaderRoute: typeof AuthenticatedPortailAdherentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portail/adherents/$id': {
      id: '/_authenticated/portail/adherents/$id'
      path: '/portail/adherents/$id'
      fullPath: '/portail/adherents/$id'
      preLoaderRoute: typeof AuthenticatedPortailAdherentsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portail/cartes/': {
      id: '/_authenticated/portail/cartes/'
      path: '/portail/cartes'
      fullPath: '/portail/cartes/'
      preLoaderRoute: typeof AuthenticatedPortailCartesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portail/cotisations/': {
      id: '/_authenticated/portail/cotisations/'
      path: '/portail/cotisations'
      fullPath: '/portail/cotisations/'
      preLoaderRoute: typeof AuthenticatedPortailCotisationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portail/partenaires/': {
      id: '/_authenticated/portail/partenaires/'
      path: '/portail/partenaires'
      fullPath: '/portail/partenaires/'
      preLoaderRoute: typeof AuthenticatedPortailPartenairesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portail/partenaires/$id': {
      id: '/_authenticated/portail/partenaires/$id'
      path: '/portail/partenaires/$id'
      fullPath: '/portail/partenaires/$id'
      preLoaderRoute: typeof AuthenticatedPortailPartenairesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portail/prises-en-charge/': {
      id: '/_authenticated/portail/prises-en-charge/'
      path: '/portail/prises-en-charge'
      fullPath: '/portail/prises-en-charge/'
      preLoaderRoute: typeof AuthenticatedPortailPrisesEnChargeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portail/remboursements/': {
      id: '/_authenticated/portail/remboursements/'
      path: '/portail/remboursements'
      fullPath: '/portail/remboursements/'
      preLoaderRoute: typeof AuthenticatedPortailRemboursementsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPortailAdherentRoute: typeof AuthenticatedPortailAdherentRoute
  AuthenticatedPortailAdministrationRoute: typeof AuthenticatedPortailAdministrationRoute
  AuthenticatedPortailAgentRoute: typeof AuthenticatedPortailAgentRoute
  AuthenticatedPortailBeneficiaireRoute: typeof AuthenticatedPortailBeneficiaireRoute
  AuthenticatedPortailCentreBienEtreRoute: typeof AuthenticatedPortailCentreBienEtreRoute
  AuthenticatedPortailCoordinationRoute: typeof AuthenticatedPortailCoordinationRoute
  AuthenticatedPortailDirectionGeneraleRoute: typeof AuthenticatedPortailDirectionGeneraleRoute
  AuthenticatedPortailEntrepriseRoute: typeof AuthenticatedPortailEntrepriseRoute
  AuthenticatedPortailEspacePartenaireRoute: typeof AuthenticatedPortailEspacePartenaireRoute
  AuthenticatedPortailFinanceRoute: typeof AuthenticatedPortailFinanceRoute
  AuthenticatedPortailGedRoute: typeof AuthenticatedPortailGedRoute
  AuthenticatedPortailHopitalRoute: typeof AuthenticatedPortailHopitalRoute
  AuthenticatedPortailLaboratoireRoute: typeof AuthenticatedPortailLaboratoireRoute
  AuthenticatedPortailMedicalRoute: typeof AuthenticatedPortailMedicalRoute
  AuthenticatedPortailMonDossierRoute: typeof AuthenticatedPortailMonDossierRoute
  AuthenticatedPortailNotificationsRoute: typeof AuthenticatedPortailNotificationsRoute
  AuthenticatedPortailParametresRoute: typeof AuthenticatedPortailParametresRoute
  AuthenticatedPortailPharmacieRoute: typeof AuthenticatedPortailPharmacieRoute
  AuthenticatedPortailRapportsRoute: typeof AuthenticatedPortailRapportsRoute
  AuthenticatedPortailRhRoute: typeof AuthenticatedPortailRhRoute
  AuthenticatedPortailSecuriteRoute: typeof AuthenticatedPortailSecuriteRoute
  AuthenticatedPortailIndexRoute: typeof AuthenticatedPortailIndexRoute
  AuthenticatedPortailAdherentsIdRoute: typeof AuthenticatedPortailAdherentsIdRoute
  AuthenticatedPortailPartenairesIdRoute: typeof AuthenticatedPortailPartenairesIdRoute
  AuthenticatedPortailAdherentsIndexRoute: typeof AuthenticatedPortailAdherentsIndexRoute
  AuthenticatedPortailCartesIndexRoute: typeof AuthenticatedPortailCartesIndexRoute
  AuthenticatedPortailCotisationsIndexRoute: typeof AuthenticatedPortailCotisationsIndexRoute
  AuthenticatedPortailPartenairesIndexRoute: typeof AuthenticatedPortailPartenairesIndexRoute
  AuthenticatedPortailPrisesEnChargeIndexRoute: typeof AuthenticatedPortailPrisesEnChargeIndexRoute
  AuthenticatedPortailRemboursementsIndexRoute: typeof AuthenticatedPortailRemboursementsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPortailAdherentRoute: AuthenticatedPortailAdherentRoute,
  AuthenticatedPortailAdministrationRoute:
    AuthenticatedPortailAdministrationRoute,
  AuthenticatedPortailAgentRoute: AuthenticatedPortailAgentRoute,
  AuthenticatedPortailBeneficiaireRoute: AuthenticatedPortailBeneficiaireRoute,
  AuthenticatedPortailCentreBienEtreRoute:
    AuthenticatedPortailCentreBienEtreRoute,
  AuthenticatedPortailCoordinationRoute: AuthenticatedPortailCoordinationRoute,
  AuthenticatedPortailDirectionGeneraleRoute:
    AuthenticatedPortailDirectionGeneraleRoute,
  AuthenticatedPortailEntrepriseRoute: AuthenticatedPortailEntrepriseRoute,
  AuthenticatedPortailEspacePartenaireRoute:
    AuthenticatedPortailEspacePartenaireRoute,
  AuthenticatedPortailFinanceRoute: AuthenticatedPortailFinanceRoute,
  AuthenticatedPortailGedRoute: AuthenticatedPortailGedRoute,
  AuthenticatedPortailHopitalRoute: AuthenticatedPortailHopitalRoute,
  AuthenticatedPortailLaboratoireRoute: AuthenticatedPortailLaboratoireRoute,
  AuthenticatedPortailMedicalRoute: AuthenticatedPortailMedicalRoute,
  AuthenticatedPortailMonDossierRoute: AuthenticatedPortailMonDossierRoute,
  AuthenticatedPortailNotificationsRoute:
    AuthenticatedPortailNotificationsRoute,
  AuthenticatedPortailParametresRoute: AuthenticatedPortailParametresRoute,
  AuthenticatedPortailPharmacieRoute: AuthenticatedPortailPharmacieRoute,
  AuthenticatedPortailRapportsRoute: AuthenticatedPortailRapportsRoute,
  AuthenticatedPortailRhRoute: AuthenticatedPortailRhRoute,
  AuthenticatedPortailSecuriteRoute: AuthenticatedPortailSecuriteRoute,
  AuthenticatedPortailIndexRoute: AuthenticatedPortailIndexRoute,
  AuthenticatedPortailAdherentsIdRoute: AuthenticatedPortailAdherentsIdRoute,
  AuthenticatedPortailPartenairesIdRoute:
    AuthenticatedPortailPartenairesIdRoute,
  AuthenticatedPortailAdherentsIndexRoute:
    AuthenticatedPortailAdherentsIndexRoute,
  AuthenticatedPortailCartesIndexRoute: AuthenticatedPortailCartesIndexRoute,
  AuthenticatedPortailCotisationsIndexRoute:
    AuthenticatedPortailCotisationsIndexRoute,
  AuthenticatedPortailPartenairesIndexRoute:
    AuthenticatedPortailPartenairesIndexRoute,
  AuthenticatedPortailPrisesEnChargeIndexRoute:
    AuthenticatedPortailPrisesEnChargeIndexRoute,
  AuthenticatedPortailRemboursementsIndexRoute:
    AuthenticatedPortailRemboursementsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ActualitesRouteChildren {
  ActualitesSlugRoute: typeof ActualitesSlugRoute
  ActualitesIndexRoute: typeof ActualitesIndexRoute
}

const ActualitesRouteChildren: ActualitesRouteChildren = {
  ActualitesSlugRoute: ActualitesSlugRoute,
  ActualitesIndexRoute: ActualitesIndexRoute,
}

const ActualitesRouteWithChildren = ActualitesRoute._addFileChildren(
  ActualitesRouteChildren,
)

interface EvenementsRouteChildren {
  EvenementsSlugRoute: typeof EvenementsSlugRoute
  EvenementsIndexRoute: typeof EvenementsIndexRoute
}

const EvenementsRouteChildren: EvenementsRouteChildren = {
  EvenementsSlugRoute: EvenementsSlugRoute,
  EvenementsIndexRoute: EvenementsIndexRoute,
}

const EvenementsRouteWithChildren = EvenementsRoute._addFileChildren(
  EvenementsRouteChildren,
)

interface PartenairesRouteChildren {
  PartenairesCentresBienEtreRoute: typeof PartenairesCentresBienEtreRoute
  PartenairesEntreprisesRoute: typeof PartenairesEntreprisesRoute
  PartenairesHopitauxRoute: typeof PartenairesHopitauxRoute
  PartenairesLaboratoiresRoute: typeof PartenairesLaboratoiresRoute
  PartenairesPharmaciesRoute: typeof PartenairesPharmaciesRoute
  PartenairesIndexRoute: typeof PartenairesIndexRoute
}

const PartenairesRouteChildren: PartenairesRouteChildren = {
  PartenairesCentresBienEtreRoute: PartenairesCentresBienEtreRoute,
  PartenairesEntreprisesRoute: PartenairesEntreprisesRoute,
  PartenairesHopitauxRoute: PartenairesHopitauxRoute,
  PartenairesLaboratoiresRoute: PartenairesLaboratoiresRoute,
  PartenairesPharmaciesRoute: PartenairesPharmaciesRoute,
  PartenairesIndexRoute: PartenairesIndexRoute,
}

const PartenairesRouteWithChildren = PartenairesRoute._addFileChildren(
  PartenairesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AProposRoute: AProposRoute,
  ActualitesRoute: ActualitesRouteWithChildren,
  AdhesionRoute: AdhesionRoute,
  AuthRoute: AuthRoute,
  CommentAdhererRoute: CommentAdhererRoute,
  ConditionsRoute: ConditionsRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ConnexionRoute: ConnexionRoute,
  ContactRoute: ContactRoute,
  EquipeRoute: EquipeRoute,
  EvenementsRoute: EvenementsRouteWithChildren,
  FaqRoute: FaqRoute,
  GalerieRoute: GalerieRoute,
  MissionRoute: MissionRoute,
  PartenairesRoute: PartenairesRouteWithChildren,
  PartenariatRoute: PartenariatRoute,
  RealisationsRoute: RealisationsRoute,
  RecrutementRoute: RecrutementRoute,
  ReinitialisationRoute: ReinitialisationRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TarifsRoute: TarifsRoute,
  TelechargementsRoute: TelechargementsRoute,
  TemoignagesRoute: TemoignagesRoute,
  ValeursRoute: ValeursRoute,
  VisionRoute: VisionRoute,
  VerifyTokenRoute: VerifyTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
